package com.example.attendme.model

enum class Department {
    IT_DEPARTMENT,
    MECH_DEPARTMENT,
    CS_DEPARTMENT,
    ELECTRICAL_DEPARTMENT,
    BIOENGINEERING_DEPARTMENT,
    AI_DATASCIENCE_DEPARTMENT,
    CHEMICAL_ENGINEERING,
    NONE
}